apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    name: db
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: db
data:
  password: cm9vdA==
  username: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
      name: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb-service
  namespace: db
spec:
  ports:
  - name: "http"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
