apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    name: db
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: db
data:
  password: cm9vdA==
  username: cm9vdA==
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: db
  labels:
    name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: db
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      role: mongodb
  template:
    metadata:
      labels:
        role: mongodb
        environment: test
        replicaset: rs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:4.4
          command:
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
          resources:
            requests:
              cpu: 0.2
              memory: 200Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-volume-claim
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-volume-claim
      spec:
        storageClassName: hostpath
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Mi
